Attempt to add Viridian Forest
- Route 2 was split in two
- Get an error : ```rgbasm -D _PIKA -o audio.o audio.asm
rgbasm -D _PIKA -o home.o home.asm
rgbasm -D _PIKA -o main.o main.asm
rgbasm -D _PIKA -o wram.o wram.asm
rgbasm -D _PIKA -o data/text/common.o data/text/common.asm
rgbasm -D _PIKA -o data/maps/map_data.o data/maps/map_data.asm
rgbasm -D _PIKA -o data/pokemon/dex_entries.o data/pokemon/dex_entries.asm
rgbasm -D _PIKA -o data/pokemon/egg_moves.o data/pokemon/egg_moves.asm
rgbasm -D _PIKA -o data/pokemon/evos_attacks.o data/pokemon/evos_attacks.asm
rgbasm -D _PIKA -o engine/movie/credits.o engine/movie/credits.asm
rgbasm -D _PIKA -o engine/overworld/events.o engine/overworld/events.asm
rgbasm -D _PIKA -o gfx/pics.o gfx/pics.asm
rgblink -n pokepika.sym -m pokepika.map -l pokepika.link -o pokepika.gbc audio.o home.o main.o wram.o data/text/common.o data/maps/map_data.o data/pokemon/dex_entries.o data/pokemon/egg_moves.o data/pokemon/evos_attacks.o engine/movie/credits.o engine/overworld/events.o gfx/pics.o gfx/sprites.o lib/mobile/main.o
error: Unknown symbol 'MAP_ROUTE_2'
make: *** [Makefile:80: pokepika.gbc] Error 1
```